Gomoku: game/game.h File Reference
game.h File Reference
Classes
struct Pos
Position in the board.
Functions
void createGame (bool load)
void gameCheck ()
Check if this is game over.
void gameOver (char symbol)
Show game over.
Function Documentation
createGame()
void createGame (bool load)
Create a game board Remember that this function Must be invoked after we Know which color is our player
Definition at line 148 of file game.c.
{
     UI color = UILoadImage(img_blackPawn);
     UI header = UICreateGrid(true);
     UI vbox = UICreateVBox(false);
     ui_grid = UICreateGrid(true);
     ui_status = UICreateLabel("");
     UISetID(header, "header");
     if (player == WHITE) {
         color = UILoadImage(img_whitePawn);
     }
     UI exit = UICreateButton("");
     gtk_button_set_image(GTK_BUTTON(exit), UILoadImage(resize(img_exit, 40, 40)));
     gtk_widget_set_tooltip_text(exit, "Exit to menu");
     UIAddClass(exit, "btn-img");
     UIEvent(exit, "clicked", eventExit, NULL);
     ui_save = UICreateButton("");
     gtk_widget_set_tooltip_text(ui_save, "Save");
     gtk_button_set_image(GTK_BUTTON(ui_save), UILoadImage(resize(img_save, 30, 30)));
     UIAddClass(ui_save, "btn-img");
     UIEvent(ui_save, "clicked", saveGame, NULL);
     UIAttach(header, exit, 0, 0, 1, 1);
     UIAttach(header, ui_save, 0, 1, 1, 1);
     UIAttach(header, color, 1, 0, 2, 2);
     UIAttach(header, ui_status, 3, 0, 3, 2);
     gtk_widget_set_size_request(ui_status, 150, 50);
     for (int y = 0; y < size; y++) {
         for (int x = 0; x < size; x++) {
             UI field = UICreateButton("");
             int* pos = malloc(2 * sizeof(int));
             UIEvent(field, "clicked", turnPawn, pos);
             UIAttach(ui_grid, field, x, y, 1, 1);
             gtk_widget_set_size_request(field, 40, 40);
             UIAddClass(field, ((x + y) % 2)
                 ? "black-field"
                 : "white-field"
             );
             btns[y * size + x] = field;
             pos[0] = x;
             pos[1] = y;
         }
     }
     UIAppend(vbox, header);
     UIAppend(vbox, ui_grid);
     UIStackAdd(ui_stack, vbox, scene_game);
     if (player == BLACK) {
         whiteDump = tlkPipeCreate(
             file_whiteDump,
             gameBuffer,
             TLK_READ
         );
         turnMove();
     }
     else {
         blackDump = tlkPipeCreate(
             file_blackDump,
             gameBuffer,
             TLK_READ
         );
         turnWait();
     }
     if (load) updateButtons();
     g_timeout_add(16, turnWaitLoop, NULL);
 }
gameCheck()
void gameCheck ()
Check if this is game over.
Definition at line 84 of file check.c.
                  {
     bool fullBoard = true;
     for (int y = 0; y < size; y++) {
         for (int x = 0; x < size; x++) {
             if (fields[y * size + x] == '0') {
                 fullBoard = false;
                 break;
             }
         }
     }
     char* file = (player == BLACK)
         ? file_blackDump
         : file_whiteDump;
     if (fullBoard) {
         UISetLabelText(ui_status, txt_endFull);
         tlkSend(file, "full");
         gameOver('f');
     }
     if (playerCheck(BLACK)) {
         UISetLabelText(ui_status, (player == BLACK ? txt_endWin : txt_endLoose));
         tlkSend(file, "black");
         gameOver('b');
     }
     if (playerCheck(WHITE)) {
         UISetLabelText(ui_status, (player == WHITE ? txt_endWin : txt_endLoose));
         tlkSend(file, "white");
         gameOver('w');
     }
 }
References BLACK, fields, file_blackDump, file_whiteDump, gameOver(), player, size, tlkSend(), txt_endFull, and ui_status.
gameOver()
void gameOver (char symbol)
Show game over.
Definition at line 111 of file game.c.
{
     UIAddClass(ui_grid, "wait");
     turn = false;
     if (!isNullized(trace)) {
         for (int i = 0; i < winReq; i++) {
             int place = trace[i].y * size + trace[i].x;
             UI field = btns[place];
             UIAddClass(field, "trace");
             if (player == (unsigned)symbol)
                 UIAddClass(field, "win");
         }
     }
     gtk_widget_set_sensitive (ui_save, false);
 }
References btns, isNullized(), player, size, trace, turn, ui_grid, ui_save, winReq, Pos::x, and Pos::y.
Referenced by gameCheck().