Gomoku: lobby/lobby.c File Reference
lobby.c File Reference
#include <include.h>
Functions
bool isLobby ()
Player joinLobby ()
Join existing lobby.
void hostLobby (bool loadFile)
Host a new lobby.
void createLobby ()
Function Documentation
createLobby()
void createLobby ()
Create a lobby scene in a stack switcher
Definition at line 46 of file lobby.c.
                    {
     UI box = UICreateVBox(true);
     UI label = UICreateLabel(txt_lobbyWait);
     UIAppend(box, label);
     UISetID(box, "jumbo");
     UIStackAdd(ui_stack, box, scene_lobby);
 }
References scene_lobby, txt_lobbyWait, and ui_stack.
Referenced by main().
hostLobby()
void hostLobby (bool loadFile)
Host a new lobby.
Definition at line 38 of file lobby.c.
{
     if (loadFile) load = true;
     UIStackVisibleName(ui_stack, scene_lobby);
     g_timeout_add(250, waitForPlayer, NULL);
     createGame(load);
     host = true;
 }
Referenced by loadGame().
isLobby()
bool isLobby ()
Check if lobby already exists
Definition at line 5 of file lobby.c.
                {
     return !access(file_lobby, F_OK);
 }
References file_lobby.
joinLobby()
Player joinLobby ()
Join existing lobby.
Definition at line 9 of file lobby.c.
                    {
     char* message = tlkRecv(file_lobby);
     connected = true;
     if (*message == 'b') return WHITE;
     if (*message == 'w') return BLACK;
     else
         fprintf(stderr,
             "Host returned bad value when "
             "trying to connect to .lobby "
             "via joinLobby() function.\n"
         );
     return NONE;
 }
References BLACK, connected, file_lobby, NONE, tlkRecv(), and WHITE.