Gomoku: talk/talk.h File Reference
talk.h File Reference
Classes
struct TlkPipe
Pipe object for object related functions.
Enumerations
enum TlkMode { TLK_READ, TLK_WRITE }
Functions
TlkPipe tlkPipeCreate (const char *filename, int buffer, TlkMode mode)
Create Pipe and return an object representation.
int tlkPipeSend (TlkPipe *this, const char *format,...)
Asynchronously send textual information to the pipe.
char * tlkPipeRecv (TlkPipe *this)
void tlkPipeRemove (TlkPipe *this)
Close opened pipe.
void tlkSetBuffer (int size)
Set buffer size (default is 1024)
int tlkSend (const char *filename, const char *format,...)
Send textual infromation through pipe synchronously.
int tlkSendAsync (const char *filename, const char *format,...)
Send textual information through pip asynchronously.
char * tlkRecv (const char *filename)
Receive textual information synchronously.
char * tlkRecvAsync (const char *filename)
Receive textual information asynchronously.
void tlkWrite (const char *filename, const char *format,...)
Write textual information to a file.
char * tlkRead (const char *filename)
Read textual information from a file.
Enumeration Type Documentation
TlkMode
enum TlkMode
Enumerator
TLK_READ
TLK_WRITE
Definition at line 4 of file talk.h.
              {
     TLK_READ,
     TLK_WRITE
 } TlkMode;
Function Documentation
tlkPipeCreate()
TlkPipe tlkPipeCreate (const char * filename, int buffer, TlkMode mode)
Create Pipe and return an object representation.
Definition at line 72 of file talk.c.
{
     int fd = 0;
     if (access(filename, F_OK)) mkfifo(filename, 0666);
     if (mode == TLK_READ)
         fd = open(filename, O_RDONLY | O_NONBLOCK);
     else
         fd = open(filename, O_WRONLY | O_NONBLOCK);
     return (TlkPipe) {
         .mode = mode,
         .buffer = buffer,
         .open = true,
         .fd = fd
     };
 }
tlkPipeRecv()
char* tlkPipeRecv (TlkPipe * this)
Asynchronously receive textual information through the pipe
Definition at line 99 of file talk.c.
{
     if (!this->open) return NULL;
     char* text = calloc(this->buffer, sizeof(char));
     int size = read(this->fd, text, this->buffer);
     if (size < 1) return NULL;
     return text;
 }
tlkPipeRemove()
void tlkPipeRemove (TlkPipe * this)
Close opened pipe.
Definition at line 107 of file talk.c.
{
     if (this->open) close(this->fd);
 }
tlkPipeSend()
int tlkPipeSend (TlkPipe * this, const char * format, ...)
Asynchronously send textual information to the pipe.
Definition at line 87 of file talk.c.
{
     if (!this->open) return -1;
     char* text = calloc(this->buffer, sizeof(char));
     va_list argptr;
     va_start(argptr, format);
     vsprintf(text, format, argptr);
     va_end(argptr);
     int state = write(this->fd, text, this->buffer);
     free(text);
     return state;
 }
tlkRead()
char* tlkRead (const char * filename)
Read textual information from a file.
Definition at line 65 of file talk.c.
{
     FILE* file = fopen(filename, "r");
     char* text = calloc(buffer, sizeof(char));
     fread(text, sizeof(char), buffer, file);
     return text;
 }
Referenced by loadGame().
tlkRecv()
char* tlkRecv (const char * filename)
Receive textual information synchronously.
Definition at line 47 of file talk.c.
{
     if (access(filename, F_OK)) mkfifo(filename, 0666);
     int fd = open(filename, O_RDONLY);
     char* text = calloc(buffer, sizeof(char));
     read(fd, text, buffer);
     close(fd);
     return text;
 }
Referenced by joinLobby().
tlkRecvAsync()
char* tlkRecvAsync (const char * filename)
Receive textual information asynchronously.
Definition at line 37 of file talk.c.
{
     if (access(filename, F_OK)) mkfifo(filename, 0666);
     int fd = open(filename, O_RDONLY | O_NONBLOCK);
     char* text = calloc(buffer, sizeof(char));
     int size = read(fd, text, buffer);
     close(fd);
     if (size < 1) return NULL;
     return text;
 }
tlkSend()
int tlkSend (const char * filename, const char * format, ...)
Send textual infromation through pipe synchronously.
Definition at line 9 of file talk.c.
{
     if (access(filename, F_OK)) mkfifo(filename, 0666);
     int fd = open(filename, O_WRONLY);
     char* text = calloc(buffer, sizeof(char));
     va_list argptr;
     va_start(argptr, format);
     vsprintf(text, format, argptr);
     va_end(argptr);
     int state = write(fd, text, buffer);
     close(fd);
     free(text);
     return state;
 }
Referenced by gameCheck().
tlkSendAsync()
int tlkSendAsync (const char * filename, const char * format, ...)
Send textual information through pip asynchronously.
Definition at line 23 of file talk.c.
{
     if (access(filename, F_OK)) mkfifo(filename, 0666);
     int fd = open(filename, O_WRONLY | O_NONBLOCK);
     char* text = calloc(buffer, sizeof(char));
     va_list argptr;
     va_start(argptr, format);
     vsprintf(text, format, argptr);
     va_end(argptr);
     int state = write(fd, text, buffer);
     close(fd);
     free(text);
     return state;
 }
tlkSetBuffer()
void tlkSetBuffer (int size)
Set buffer size (default is 1024)
Definition at line 5 of file talk.c.
{
     buffer = size;
 }
tlkWrite()
void tlkWrite (const char * filename, const char * format, ...)
Write textual information to a file.
Definition at line 56 of file talk.c.
{
     FILE* file = fopen(filename, "w");
     va_list argptr;
     va_start(argptr, format);
     vfprintf(file, format, argptr);
     va_end(argptr);
     fclose(file);
 }
Referenced by saveGame().